# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Vimdows_config = debug

else ifeq ($(config),release)
  Vimdows_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Vimdows

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Vimdows:
ifneq (,$(Vimdows_config))
	@echo "==== Building Vimdows ($(Vimdows_config)) ===="
	@${MAKE} --no-print-directory -C . -f Vimdows.make config=$(Vimdows_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Vimdows.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Vimdows"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"